# Site settings
repository: jekyll-fr/jekyll-fr.github.io
title: Jekyll-fr
email: contact@jekyll-fr.org
description: Communauté francophone des utilisateurs de Jekyll
baseurl: ""
url: "http://jekyll-fr.github.io"
permalink: /:year/:month/:day/:title/
timezone: Europe/Paris


twitter:
    username: jekyll_fr
github:
    username: jekyll-fr

social:
  type: organization
  links:
    - https://twitter.com/jekyll_fr
    - https://github.com/jekyll-fr

markdown: kramdown
kramdown:
   input: GFM

exclude:
    - .editorconfig
    - .gitignore
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-paginate
