# Site settings
title: Jekyll-fr
email: contact@jekyll-fr.org
description: Communauté francophone des utilisateurs de Jekyll
baseurl: ""
url: "http://jekyll-fr.org"
permalink: /:year/:month/:day/:title/
timezone: Europe/Paris
lang: fr

repository: jekyll-fr/jekyll-fr.github.io
branch: master

twitter:
    username: jekyll_fr
github:
    username: jekyll-fr

social:
  type: organization
  links:
    - https://twitter.com/jekyll_fr
    - https://github.com/jekyll-fr

analytics:
  google :
    tracking_id : UA-75833986-1

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

sass:
    style: compressed

exclude:
    - .editorconfig
    - .gitignore
    - .forestryio
    - .rubocop.yml
    - .travis.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true

gems:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-mentions"
  - "jekyll-avatar"
  - "jekyll-paginate"
  - "jekyll-github-metadata"
